# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7250fa0e817a6b80f915271f0928722124a9aee4ae33c2dba5482730e737e3a9a627c8213a47ed7a0dd9744415e163be59cb665b93e5df782b7babc99ecbe7

test:
  secret_key_base: da0a029a5b0d6e290bb277174bfc07882d3080bcf649669f6ffd0f73c57e160e69b1ae02ce0760c3587e89346cee12df0bf9002f3deaefe2df1f5793f1586903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
